batch_size: 1024
ckpt_every: 5000
cold_init_eps: 1.0e-12
contrastive_window: 32
dataset_id: D4RL/antmaze/umaze-v1
datasets_path: /scratch/users/asattira/mirage/minari
device: cuda
dyn_hidden_dim: 256
dyn_n_hidden: 2
eval_batch_size: 1024
eval_batches: 16
eval_every: 2500
fwd_weight: 0.1
grad_clip: 10.0
hidden_dim: 512
input_mode: full
inv_weight: 1.0
l2_normalize: true
latent_dim: 16
load_default_checkpoint: true
log_every: 200
log_root: /scratch/users/asattira/mirage/runs_encoder
lr: 0.0003
mask_prob: 0.3
n_hidden: 3
nce_temperature: 0.1
nce_weight: 1.0
run_name: dual_input_masked
seed: 0
total_steps: 50000
val_frac: 0.05
wandb: false
wandb_entity: samratsahoo-stanford-university
wandb_project: MIRAGE
weight_decay: 0.0
