env:
  env_type: antmaze
  env_id: AntMaze_UMaze-v5
  reward_type: sparse
  continuing_task: true
  reset_target: false
  max_episode_steps: 1000
  goal_size: 2
  capture_video: false
  video_every: 1000
  use_cuda_graph: false

ppo:
  seed: 1
  load_default_checkpoint: true

  state_mode: latent
  unified_encoder_path: runs_encoder/dual_input_masked_recon/encoder_best.pt
  goal_conditioning: ['latent_goal']
  subgoal_mode: ""
  subgoal_radius: 1.5

  num_envs: 16384
  num_steps: 16
  num_minibatches: 32
  update_epochs: 10
  learning_rate: 0.0003
  anneal_lr: true
  gamma: 0.99
  gae_lambda: 0.95
  norm_adv: true
  clip_coef: 0.2
  clip_vloss: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: null

wandb:
  track: true
  project: MIRAGE
  entity: null

train:
  total_timesteps: 100000000
  save_model: true
  save_freq: 5000000
  eval_freq: 2000000
  eval_episodes: 256
