dataset_id: D4RL/antmaze/umaze-v1
datasets_path: /scratch/users/asattira/mirage/minari

input_mode: xy
run_name: xy2d
log_root: /scratch/users/asattira/mirage/runs
ckpt_root: /scratch/users/asattira/mirage/ckpts

latent_dim: 16
hidden_dim: 512
n_hidden: 3
cold_init_eps: 1.0e-12
l2_normalize: true

dyn_hidden_dim: 256
dyn_n_hidden: 2

nce_weight: 1.0
inv_weight: 1.0
fwd_weight: 0.1
nce_temperature: 0.1
contrastive_window: 32

batch_size: 1024
total_steps: 200000
lr: 3.0e-4
weight_decay: 0.0
grad_clip: 10.0

log_every: 200
eval_every: 5000
ckpt_every: 10000
eval_batches: 16
eval_batch_size: 1024

val_frac: 0.05

seed: 0
device: cuda

wandb: true
wandb_project: MIRAGE
wandb_entity: samratsahoo-stanford-university
